create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table produto (ativo bit not null, preco decimal(38,2) not null, id bigint not null auto_increment, restaurante_id bigint not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table restaurante (taxa_frete decimal(38,2) not null, cozinha_id bigint not null, data_atualizacao datetime(6) not null, data_cadastro datetime(6) not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table usuario (data_cadastro datetime(6) not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario_grupo (grupo_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao (id);
alter table grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
alter table usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo (id);
alter table usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario (id);
INSERT INTO cozinha (nome) VALUES ('Tailandesa');
INSERT INTO cozinha (nome) VALUES ('Indiana');
INSERT INTO estado (nome) VALUES ('Estado ABC');
INSERT INTO estado (nome) VALUES ('Estado DEF');
INSERT INTO estado (nome) VALUES ('Estado GHI');
INSERT INTO estado (nome) VALUES ('Estado JKL');
INSERT INTO estado (nome) VALUES ('Estado MNO');
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade ABC', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade DEF', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade GHI', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade JKL', 2);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade MNO', 2);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade PQR', 3);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade STU', 4);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade VXW', 4);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade YZA', 5);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_complemento, endereco_bairro, data_cadastro, data_atualizacao) VALUES ('Casa Velha', 0.7, 1, 1, '21050-740', 'Rua Eudoro Berlinck', '10', '214', 'Higienopolis', utc_timestamp, utc_timestamp);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) VALUES ('Outback', 1.2, 2, utc_timestamp, utc_timestamp);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) VALUES ('O Camarão', 4.5, 1, utc_timestamp, utc_timestamp);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto A', 6.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto B', 7.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto C', 3.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto D', 6.5, true, 2);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto E', 6.5, true, 3);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto F', 6.5, true, 3);
INSERT INTO forma_pagamento (descricao) VALUES ('Debito em conta');
INSERT INTO forma_pagamento (descricao) VALUES ('Cartao de credito');
INSERT INTO forma_pagamento (descricao) VALUES ('Pix');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) VALUES (1,1), (1,2), (1,3), (2,3), (3,2), (3,3);
create table cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table produto (ativo bit not null, preco decimal(38,2) not null, id bigint not null auto_increment, restaurante_id bigint not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table restaurante (taxa_frete decimal(38,2) not null, cozinha_id bigint not null, data_atualizacao datetime(6) not null, data_cadastro datetime(6) not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table usuario (data_cadastro datetime(6) not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario_grupo (grupo_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao (id);
alter table grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
alter table usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo (id);
alter table usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario (id);
INSERT INTO cozinha (nome) VALUES ('Tailandesa');
INSERT INTO cozinha (nome) VALUES ('Indiana');
INSERT INTO estado (nome) VALUES ('Estado ABC');
INSERT INTO estado (nome) VALUES ('Estado DEF');
INSERT INTO estado (nome) VALUES ('Estado GHI');
INSERT INTO estado (nome) VALUES ('Estado JKL');
INSERT INTO estado (nome) VALUES ('Estado MNO');
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade ABC', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade DEF', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade GHI', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade JKL', 2);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade MNO', 2);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade PQR', 3);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade STU', 4);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade VXW', 4);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade YZA', 5);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_complemento, endereco_bairro, data_cadastro, data_atualizacao) VALUES ('Casa Velha', 0.7, 1, 1, '21050-740', 'Rua Eudoro Berlinck', '10', '214', 'Higienopolis', utc_timestamp, utc_timestamp);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) VALUES ('Outback', 1.2, 2, utc_timestamp, utc_timestamp);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) VALUES ('O Camarão', 4.5, 1, utc_timestamp, utc_timestamp);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto A', 6.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto B', 7.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto C', 3.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto D', 6.5, true, 2);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto E', 6.5, true, 3);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto F', 6.5, true, 3);
INSERT INTO forma_pagamento (descricao) VALUES ('Debito em conta');
INSERT INTO forma_pagamento (descricao) VALUES ('Cartao de credito');
INSERT INTO forma_pagamento (descricao) VALUES ('Pix');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) VALUES (1,1), (1,2), (1,3), (2,3), (3,2), (3,3);
create table cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table produto (ativo bit not null, preco decimal(38,2) not null, id bigint not null auto_increment, restaurante_id bigint not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table restaurante (taxa_frete decimal(38,2) not null, cozinha_id bigint not null, data_atualizacao datetime(6) not null, data_cadastro datetime(6) not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table usuario (data_cadastro datetime(6) not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario_grupo (grupo_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao (id);
alter table grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
alter table usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo (id);
alter table usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario (id);
INSERT INTO cozinha (nome) VALUES ('Tailandesa');
INSERT INTO cozinha (nome) VALUES ('Indiana');
INSERT INTO estado (nome) VALUES ('Estado ABC');
INSERT INTO estado (nome) VALUES ('Estado DEF');
INSERT INTO estado (nome) VALUES ('Estado GHI');
INSERT INTO estado (nome) VALUES ('Estado JKL');
INSERT INTO estado (nome) VALUES ('Estado MNO');
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade ABC', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade DEF', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade GHI', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade JKL', 2);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade MNO', 2);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade PQR', 3);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade STU', 4);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade VXW', 4);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade YZA', 5);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_complemento, endereco_bairro, data_cadastro, data_atualizacao) VALUES ('Casa Velha', 0.7, 1, 1, '21050-740', 'Rua Eudoro Berlinck', '10', '214', 'Higienopolis', utc_timestamp, utc_timestamp);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) VALUES ('Outback', 1.2, 2, utc_timestamp, utc_timestamp);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) VALUES ('O Camarão', 4.5, 1, utc_timestamp, utc_timestamp);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto A', 6.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto B', 7.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto C', 3.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto D', 6.5, true, 2);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto E', 6.5, true, 3);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto F', 6.5, true, 3);
INSERT INTO forma_pagamento (descricao) VALUES ('Debito em conta');
INSERT INTO forma_pagamento (descricao) VALUES ('Cartao de credito');
INSERT INTO forma_pagamento (descricao) VALUES ('Pix');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) VALUES (1,1), (1,2), (1,3), (2,3), (3,2), (3,3);
create table cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table produto (ativo bit not null, preco decimal(38,2) not null, id bigint not null auto_increment, restaurante_id bigint not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table restaurante (taxa_frete decimal(38,2) not null, cozinha_id bigint not null, data_atualizacao datetime(6) not null, data_cadastro datetime(6) not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table usuario (data_cadastro datetime(6) not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario_grupo (grupo_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao (id);
alter table grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
alter table usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo (id);
alter table usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario (id);
INSERT INTO cozinha (nome) VALUES ('Tailandesa');
INSERT INTO cozinha (nome) VALUES ('Indiana');
INSERT INTO estado (nome) VALUES ('Estado ABC');
INSERT INTO estado (nome) VALUES ('Estado DEF');
INSERT INTO estado (nome) VALUES ('Estado GHI');
INSERT INTO estado (nome) VALUES ('Estado JKL');
INSERT INTO estado (nome) VALUES ('Estado MNO');
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade ABC', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade DEF', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade GHI', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade JKL', 2);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade MNO', 2);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade PQR', 3);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade STU', 4);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade VXW', 4);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade YZA', 5);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_complemento, endereco_bairro, data_cadastro, data_atualizacao) VALUES ('Casa Velha', 0.7, 1, 1, '21050-740', 'Rua Eudoro Berlinck', '10', '214', 'Higienopolis', utc_timestamp, utc_timestamp);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) VALUES ('Outback', 1.2, 2, utc_timestamp, utc_timestamp);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) VALUES ('O Camarão', 4.5, 1, utc_timestamp, utc_timestamp);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto A', 6.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto B', 7.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto C', 3.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto D', 6.5, true, 2);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto E', 6.5, true, 3);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto F', 6.5, true, 3);
INSERT INTO forma_pagamento (descricao) VALUES ('Debito em conta');
INSERT INTO forma_pagamento (descricao) VALUES ('Cartao de credito');
INSERT INTO forma_pagamento (descricao) VALUES ('Pix');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) VALUES (1,1), (1,2), (1,3), (2,3), (3,2), (3,3);
create table cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table produto (ativo bit not null, preco decimal(38,2) not null, id bigint not null auto_increment, restaurante_id bigint not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table restaurante (taxa_frete decimal(38,2) not null, cozinha_id bigint not null, data_atualizacao datetime(6) not null, data_cadastro datetime(6) not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table usuario (data_cadastro datetime(6) not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario_grupo (grupo_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao (id);
alter table grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
alter table usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo (id);
alter table usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario (id);
INSERT INTO cozinha (nome) VALUES ('Tailandesa');
INSERT INTO cozinha (nome) VALUES ('Indiana');
INSERT INTO estado (nome) VALUES ('Estado ABC');
INSERT INTO estado (nome) VALUES ('Estado DEF');
INSERT INTO estado (nome) VALUES ('Estado GHI');
INSERT INTO estado (nome) VALUES ('Estado JKL');
INSERT INTO estado (nome) VALUES ('Estado MNO');
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade ABC', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade DEF', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade GHI', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade JKL', 2);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade MNO', 2);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade PQR', 3);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade STU', 4);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade VXW', 4);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade YZA', 5);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_complemento, endereco_bairro, data_cadastro, data_atualizacao) VALUES ('Casa Velha', 0.7, 1, 1, '21050-740', 'Rua Eudoro Berlinck', '10', '214', 'Higienopolis', utc_timestamp, utc_timestamp);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) VALUES ('Outback', 1.2, 2, utc_timestamp, utc_timestamp);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) VALUES ('O Camarão', 4.5, 1, utc_timestamp, utc_timestamp);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto A', 6.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto B', 7.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto C', 3.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto D', 6.5, true, 2);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto E', 6.5, true, 3);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto F', 6.5, true, 3);
INSERT INTO forma_pagamento (descricao) VALUES ('Debito em conta');
INSERT INTO forma_pagamento (descricao) VALUES ('Cartao de credito');
INSERT INTO forma_pagamento (descricao) VALUES ('Pix');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) VALUES (1,1), (1,2), (1,3), (2,3), (3,2), (3,3);
create table cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table produto (ativo bit not null, preco decimal(38,2) not null, id bigint not null auto_increment, restaurante_id bigint not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table restaurante (taxa_frete decimal(38,2) not null, cozinha_id bigint not null, data_atualizacao datetime(6) not null, data_cadastro datetime(6) not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table usuario (data_cadastro datetime(6) not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario_grupo (grupo_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao (id);
alter table grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
alter table usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo (id);
alter table usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario (id);
INSERT INTO cozinha (nome) VALUES ('Tailandesa');
INSERT INTO cozinha (nome) VALUES ('Indiana');
INSERT INTO estado (nome) VALUES ('Estado ABC');
INSERT INTO estado (nome) VALUES ('Estado DEF');
INSERT INTO estado (nome) VALUES ('Estado GHI');
INSERT INTO estado (nome) VALUES ('Estado JKL');
INSERT INTO estado (nome) VALUES ('Estado MNO');
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade ABC', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade DEF', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade GHI', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade JKL', 2);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade MNO', 2);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade PQR', 3);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade STU', 4);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade VXW', 4);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade YZA', 5);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_complemento, endereco_bairro, data_cadastro, data_atualizacao) VALUES ('Casa Velha', 0.7, 1, 1, '21050-740', 'Rua Eudoro Berlinck', '10', '214', 'Higienopolis', utc_timestamp, utc_timestamp);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) VALUES ('Outback', 1.2, 2, utc_timestamp, utc_timestamp);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) VALUES ('O Camarão', 4.5, 1, utc_timestamp, utc_timestamp);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto A', 6.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto B', 7.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto C', 3.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto D', 6.5, true, 2);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto E', 6.5, true, 3);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto F', 6.5, true, 3);
INSERT INTO forma_pagamento (descricao) VALUES ('Debito em conta');
INSERT INTO forma_pagamento (descricao) VALUES ('Cartao de credito');
INSERT INTO forma_pagamento (descricao) VALUES ('Pix');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) VALUES (1,1), (1,2), (1,3), (2,3), (3,2), (3,3);
create table cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table produto (ativo bit not null, preco decimal(38,2) not null, id bigint not null auto_increment, restaurante_id bigint not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table restaurante (taxa_frete decimal(38,2) not null, cozinha_id bigint not null, data_atualizacao datetime(6) not null, data_cadastro datetime(6) not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table usuario (data_cadastro datetime(6) not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario_grupo (grupo_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao (id);
alter table grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
alter table usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo (id);
alter table usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario (id);
INSERT INTO cozinha (nome) VALUES ('Tailandesa');
INSERT INTO cozinha (nome) VALUES ('Indiana');
INSERT INTO estado (nome) VALUES ('Estado ABC');
INSERT INTO estado (nome) VALUES ('Estado DEF');
INSERT INTO estado (nome) VALUES ('Estado GHI');
INSERT INTO estado (nome) VALUES ('Estado JKL');
INSERT INTO estado (nome) VALUES ('Estado MNO');
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade ABC', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade DEF', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade GHI', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade JKL', 2);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade MNO', 2);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade PQR', 3);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade STU', 4);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade VXW', 4);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade YZA', 5);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_complemento, endereco_bairro, data_cadastro, data_atualizacao) VALUES ('Casa Velha', 0.7, 1, 1, '21050-740', 'Rua Eudoro Berlinck', '10', '214', 'Higienopolis', utc_timestamp, utc_timestamp);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) VALUES ('Outback', 1.2, 2, utc_timestamp, utc_timestamp);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) VALUES ('O Camarão', 4.5, 1, utc_timestamp, utc_timestamp);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto A', 6.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto B', 7.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto C', 3.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto D', 6.5, true, 2);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto E', 6.5, true, 3);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto F', 6.5, true, 3);
INSERT INTO forma_pagamento (descricao) VALUES ('Debito em conta');
INSERT INTO forma_pagamento (descricao) VALUES ('Cartao de credito');
INSERT INTO forma_pagamento (descricao) VALUES ('Pix');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) VALUES (1,1), (1,2), (1,3), (2,3), (3,2), (3,3);
create table cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table produto (ativo bit not null, preco decimal(38,2) not null, id bigint not null auto_increment, restaurante_id bigint not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table restaurante (taxa_frete decimal(38,2) not null, cozinha_id bigint not null, data_atualizacao datetime(6) not null, data_cadastro datetime(6) not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table usuario (data_cadastro datetime(6) not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario_grupo (grupo_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao (id);
alter table grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
alter table usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo (id);
alter table usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario (id);
INSERT INTO cozinha (nome) VALUES ('Tailandesa');
INSERT INTO cozinha (nome) VALUES ('Indiana');
INSERT INTO estado (nome) VALUES ('Estado ABC');
INSERT INTO estado (nome) VALUES ('Estado DEF');
INSERT INTO estado (nome) VALUES ('Estado GHI');
INSERT INTO estado (nome) VALUES ('Estado JKL');
INSERT INTO estado (nome) VALUES ('Estado MNO');
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade ABC', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade DEF', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade GHI', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade JKL', 2);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade MNO', 2);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade PQR', 3);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade STU', 4);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade VXW', 4);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade YZA', 5);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_complemento, endereco_bairro, data_cadastro, data_atualizacao) VALUES ('Casa Velha', 0.7, 1, 1, '21050-740', 'Rua Eudoro Berlinck', '10', '214', 'Higienopolis', utc_timestamp, utc_timestamp);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) VALUES ('Outback', 1.2, 2, utc_timestamp, utc_timestamp);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) VALUES ('O Camarão', 4.5, 1, utc_timestamp, utc_timestamp);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto A', 6.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto B', 7.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto C', 3.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto D', 6.5, true, 2);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto E', 6.5, true, 3);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto F', 6.5, true, 3);
INSERT INTO forma_pagamento (descricao) VALUES ('Debito em conta');
INSERT INTO forma_pagamento (descricao) VALUES ('Cartao de credito');
INSERT INTO forma_pagamento (descricao) VALUES ('Pix');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) VALUES (1,1), (1,2), (1,3), (2,3), (3,2), (3,3);
create table cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table produto (ativo bit not null, preco decimal(38,2) not null, id bigint not null auto_increment, restaurante_id bigint not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table restaurante (taxa_frete decimal(38,2) not null, cozinha_id bigint not null, data_atualizacao datetime(6) not null, data_cadastro datetime(6) not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table usuario (data_cadastro datetime(6) not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario_grupo (grupo_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao (id);
alter table grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
alter table usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo (id);
alter table usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario (id);
INSERT INTO cozinha (nome) VALUES ('Tailandesa');
INSERT INTO cozinha (nome) VALUES ('Indiana');
INSERT INTO estado (nome) VALUES ('Estado ABC');
INSERT INTO estado (nome) VALUES ('Estado DEF');
INSERT INTO estado (nome) VALUES ('Estado GHI');
INSERT INTO estado (nome) VALUES ('Estado JKL');
INSERT INTO estado (nome) VALUES ('Estado MNO');
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade ABC', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade DEF', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade GHI', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade JKL', 2);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade MNO', 2);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade PQR', 3);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade STU', 4);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade VXW', 4);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade YZA', 5);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_complemento, endereco_bairro, data_cadastro, data_atualizacao) VALUES ('Casa Velha', 0.7, 1, 1, '21050-740', 'Rua Eudoro Berlinck', '10', '214', 'Higienopolis', utc_timestamp, utc_timestamp);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) VALUES ('Outback', 1.2, 2, utc_timestamp, utc_timestamp);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) VALUES ('O Camarão', 4.5, 1, utc_timestamp, utc_timestamp);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto A', 6.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto B', 7.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto C', 3.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto D', 6.5, true, 2);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto E', 6.5, true, 3);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto F', 6.5, true, 3);
INSERT INTO forma_pagamento (descricao) VALUES ('Debito em conta');
INSERT INTO forma_pagamento (descricao) VALUES ('Cartao de credito');
INSERT INTO forma_pagamento (descricao) VALUES ('Pix');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) VALUES (1,1), (1,2), (1,3), (2,3), (3,2), (3,3);
create table cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table produto (ativo bit not null, preco decimal(38,2) not null, id bigint not null auto_increment, restaurante_id bigint not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table restaurante (taxa_frete decimal(38,2) not null, cozinha_id bigint not null, data_atualizacao datetime(6) not null, data_cadastro datetime(6) not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table usuario (data_cadastro datetime(6) not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario_grupo (grupo_id bigint not null, usuario_id bigint not null) engine=InnoDB;
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao (id);
alter table grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
alter table usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo (id);
alter table usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario (id);
INSERT INTO cozinha (nome) VALUES ('Tailandesa');
INSERT INTO cozinha (nome) VALUES ('Indiana');
INSERT INTO estado (nome) VALUES ('Estado ABC');
INSERT INTO estado (nome) VALUES ('Estado DEF');
INSERT INTO estado (nome) VALUES ('Estado GHI');
INSERT INTO estado (nome) VALUES ('Estado JKL');
INSERT INTO estado (nome) VALUES ('Estado MNO');
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade ABC', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade DEF', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade GHI', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade JKL', 2);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade MNO', 2);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade PQR', 3);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade STU', 4);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade VXW', 4);
INSERT INTO cidade (nome, estado_id) VALUES ('Cidade YZA', 5);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_complemento, endereco_bairro, data_cadastro, data_atualizacao) VALUES ('Casa Velha', 0.7, 1, 1, '21050-740', 'Rua Eudoro Berlinck', '10', '214', 'Higienopolis', utc_timestamp, utc_timestamp);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) VALUES ('Outback', 1.2, 2, utc_timestamp, utc_timestamp);
INSERT INTO restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) VALUES ('O Camarão', 4.5, 1, utc_timestamp, utc_timestamp);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto A', 6.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto B', 7.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto C', 3.5, true, 1);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto D', 6.5, true, 2);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto E', 6.5, true, 3);
INSERT INTO produto (nome,preco,ativo, restaurante_id) VALUES ('Produto F', 6.5, true, 3);
INSERT INTO forma_pagamento (descricao) VALUES ('Debito em conta');
INSERT INTO forma_pagamento (descricao) VALUES ('Cartao de credito');
INSERT INTO forma_pagamento (descricao) VALUES ('Pix');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO permissao (nome, descricao) VALUES ('Permissao ABC','Descricao da permissao ABC');
INSERT INTO restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) VALUES (1,1), (1,2), (1,3), (2,3), (3,2), (3,3);
